config/routes.rb
MusicalWaves::Application.routes.draw do
  

  root :to => 'main#home'
  
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  

  match 'music', :to => "main#music"

  match 'artists', :to => "artists#artists"
  
  match '/concerts', :to => "programs#index"

  match '/artists/:name', :to => "artists#show", as: 'a_show'

  match '/concerts/:title', :to => "programs#show", as: 'p_show'

  resources :artists do
    resource :show
  end

  resources :programs do
    resource :show
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  attr_accessible :bio, :instrument, :name, :picture, :program_ids
  validates_uniqueness_of :name
  validates_presence_of  :name
  has_many :artist_performances, :dependent => :destroy
  has_many :programs, :through => :artist_performances
  accepts_nested_attributes_for :programs
end

app/models/artist_performance.rb
class ArtistPerformance < ActiveRecord::Base
  attr_accessible :artist_id, :program_id
  belongs_to :artist
  belongs_to :program
end

app/models/concert.rb
class Concert < ActiveRecord::Base
  attr_accessible :date, :location, :price, :program_id, :ticket_website, :time
  validates_presence_of :date, :location, :program_id, :time
  belongs_to :program
  accepts_nested_attributes_for :program
end

app/models/program.rb
class Program < ActiveRecord::Base
  attr_accessible :description, :title, :website, :artist_ids, :concert_ids, :concerts_attributes
  validates_presence_of :title, :description
  validates_uniqueness_of :title
  has_many :concerts, :dependent => :destroy
  has_many :artist_performances, :dependent => :destroy
  has_many :artists, :through => :artist_performances
  accepts_nested_attributes_for :artists
  accepts_nested_attributes_for :concerts, :allow_destroy => true

  def date_of_first_performance
  	list = self.concerts.order("date ASC")
  	if list.empty?
  		return Time.now.to_date + 2.year
  	else
  		return list.first.date
  	end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper :all
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
	def show
		@artist = Artist.find_by_name(params[:name])
		@title = @artist.name
	end	

	def artists
		@title = "Artists"
		@artists = Artist.all
	end
end

app/controllers/concerts_controller.rb
class ProgramsController < InheritedResources::Base

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def home
  	@title = "Home"
  end

  def music
  	@title = "Music"
  end

  def concerts
  	@title = "Concerts"
  end
end

app/controllers/programs_controller.rb
class ProgramsController < InheritedResources::Base
	def index
  	@title = "Concerts"
  	@programs = Program.all
  end

	def show
		@program = Program.find_by_title(params[:title])
		@title = @program.title
	end	

end

app/helpers/application_helper.rb
module ApplicationHelper
	# Return a title on a per-page basis
	def page_title
		base_title = "Musical Waves"
		if @title.nil?
			base_title
		else
			"#{base_title} | #{@title}"
		end
	end

	def page
		@title unless @title.nil?
	end

end

app/helpers/artists_helper.rb
module ArtistsHelper
	def last_name(artist)
		artist.name.split(" ")[-1]
	end

	def first_name(artist)
		artist.name.split(" ")[0]
	end

	def artist_name_sort(artists)
        artists.sort { |a, b| [last_name(a), first_name(a)]  <=> [last_name(b), first_name(b)] }
    end

	def num_programs(artist)
		artist.programs.count
	end

	def artists_sorted(artists)
		artists.sort { |a, b| 
			[artist_priority(b), num_programs(b), last_name(a), first_name(a)] <=> 
			[artist_priority(a), num_programs(a), last_name(b), first_name(b)] }
	end

	def performance_list(artist)
		p_array = Array.new
        future_performances(artist).sort { |a, b| a.title  <=> b.title }.each do |program|
        	p_array.push(link_to program.title, p_show_path(:title => program.title))
        end
        p_array.join(",  ")
	end

	def future_performances(artist)
		future_programs(artist.programs)
	end

	def artist_priority(artist)
		if future_performances(artist) == []
			return 0
		else
			return 1
		end
	end
end

app/helpers/main_helper.rb
module MainHelper

end

app/helpers/programs_helper.rb
module ProgramsHelper

	 def artist_list(program)
		  a_array = Array.new
        program.artists.sort { |a, b| [last_name(a), first_name(a)]  <=> [last_name(b), first_name(b)] }.each do |artist|
        	a_array.push(link_to artist.name, a_show_path(:name => artist.name))
        end
        a_array.join(", ")
    end

    def program_sort(programs)
    	programs.sort { |a, b| a.date_of_first_performance <=> b.date_of_first_performance }
    end

    def reverse_program_sort(programs)
    	programs.sort { |a, b| b.date_of_first_performance <=> a.date_of_first_performance  }
    end

    def program_performed(program)
    	counter = 0
    	counter = counter + 1 if program.concerts == []
   		program.concerts.each do |concert|
   			if Time.now.to_date < concert.date + 1.day
   				counter = counter + 1
   				break
   			end
   			break if counter == 1
   		end
   		if counter == 1
   			return false
   		else
   			return true
   		end
   	end

   	def next_program
   		programs = future_programs(Program.all)
   		next_program = programs[0] unless programs == []
   		programs.each do |program|
   			if program.date_of_first_performance < next_program.date_of_first_performance
   				next_program = program
   			end
   		end
   		return next_program
   	end

   	def future_programs(programs)
   		future_programs = []
   		programs.each do |program|
   			future_programs.push(program) if !program_performed(program)
   		end
   		return future_programs
   	end

   	def past_programs(programs)
   		past_programs = []
   		programs.each do |program|
   			past_programs.push(program) if program_performed(program)
   		end
   		return past_programs
   	end

    def concert_sort(program)
    	program.concerts.sort { |a, b| [a.date, get_time(a)] <=> [b.date, get_time(b)] }
    end

    def get_time(concert)
    	begin
    		DateTime.parse(concert.time).strftime("%H:%M")
    	rescue
    		"23:59"
    	end
    end
end

app/views/artists/artists.html.erb
<h1>Artists</h1>

<section class="list">
	<% artists_sorted(@artists).each do |artist| %>
	<article id="artist">
		<h2><%= link_to artist.name, a_show_path(:name => artist.name) %></h2>
		<h5><%= artist.instrument %></h5>

		<section class="text">
			<% if !artist.picture.empty? %>
				<a href="<%= artist.picture %>"><img src="<%= artist.picture %>" alt="" class="s_img" /></a>
			<% end %>
			<p>
				<%= truncate(strip_tags(artist.bio), :length=>290) %>
			</p>
		</section>

		<a href="<%= a_show_path(:name => artist.name) %>" class="button">Read More</a>

	</article>
	<% end %>
</section>

app/views/artists/show.html.erb
<article id="artist">
	<h2><%= @artist.name %></h2>
	<h4><%= @artist.instrument %></h4>
	<% if !@artist.picture.empty? %>
		<a href="<%= @artist.picture %>" class="b_img"><img src="<%= @artist.picture %>" alt="" class="b_img" /></a>
	<% end %>
	<% if future_programs(@artist.programs).count > 0 %>
		<p></p>
		<h5>Upcoming Performances:</h5>
		<h4><%= performance_list(@artist).html_safe %></h4>
	<% end %>
	<section class="text">
		<p>
			<%= @artist.bio.html_safe %>
		</p>
	</section>
</article>

<stron><%= link_to "Back to Artists", artists_path %></strong>

app/views/layouts/_footer.html.erb
<h1><%= link_to "Home", root_path %>   |   
<%= link_to "Artists", artists_path %>   |   
<%= link_to "Concerts", concerts_path %>   |  
<%= link_to "Music", music_path %></h1>

<h1>&copy; <%= Time.now.year %> Musical Waves | Photo by Tom Linford | Website Design by Andrew Linford</h1>

app/views/layouts/_head.html.erb
<head>
  <meta charset="utf-8">
  <title><%= page_title %></title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Lato:700' rel='stylesheet' type='text/css'>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

app/views/layouts/_header.html.erb
<section id="header_bar">
	<section id="logo">
		<h1><%= link_to "Musical Waves", root_path %></h1>
	</section>
	<section id="menu">
		<ul>
			<% if page == "Home" %>
				<li class="current_page_item"><%= link_to "Home", root_path %></li>
				<li><%= link_to "Artists", artists_path %></li>
				<li><%= link_to "Concerts", concerts_path %></li>
				<li><%= link_to "Music", music_path %></li>
			<% elsif page == "Artists" %>
				<li><%= link_to "Home", root_path %></li>
				<li class="current_page_item"><%= link_to "Artists", artists_path %></li>
				<li><%= link_to "Concerts", concerts_path %></li>
				<li><%= link_to "Music", music_path %></li>
			<% elsif page == "Concerts" %>
				<li><%= link_to "Home", root_path %></li>
				<li><%= link_to "Artists", artists_path %></li>
				<li class="current_page_item"><%= link_to "Concerts", concerts_path %></li>
				<li><%= link_to "Music", music_path %></li>
			<% elsif page == "Music" %>
				<li><%= link_to "Home", root_path %></li>
				<li><%= link_to "Artists", artists_path %></li>
				<li><%= link_to "Concerts", programs_path %></li>
				<li class="current_page_item"><%= link_to "Music", music_path %></li>
			<% else %>
				<li><%= link_to "Home", root_path %></li>
				<li><%= link_to "Artists", artists_path %></li>
				<li><%= link_to "Concerts", concerts_path %></li>
				<li><%= link_to "Music", music_path %></li>
			<% end %>
		</ul>
	</section>
</section>

app/views/layouts/_sidebar.html.erb
<% if page == "Artists" %>
	<section>
		<h4>Artists</h4>
		<ol class="sidebar-list">
			<% artist_name_sort(Artist.all).each do |artist| %>
				<li><%= link_to artist.name, a_show_path(:name => artist.name) %></li>
			<% end %>
		</ol>
	</section>

<% elsif page == "Concerts" %>
	<section>
		<h4>Concerts</h4>
		<ol class="sidebar-list">
			<% program_sort(future_programs(Program.all)).each do |program| %>
				<li><%= link_to program.title, p_show_path(:title => program.title) %></li>
			<% end %>
		</ol>
	</section>
<% elsif next_program != nil %>
	<section>
		<h5>Next Performance</h5>
		<ol class="sidebar-list">
			<li><%= link_to next_program.title, p_show_path(:title => next_program.title) %></li>
			<li><%= next_program.date_of_first_performance.strftime ("%b %d, %Y") %></li>

		</ol>
	</section>
<% else %>
<% end %>

<section >
	<h5>Questions?</h5>
	<ul class="sidebar-list"><li>Feel free to <a href="mailto:musicalwavessf@gmail.com?Subject=Website Feedback" target="_top">email</a> us.</ul></li>
</section>

<section class="signup-box">
	<h5>Sign Up for the Musical Waves E-Mail List!</h5>


	<!-- Signup Form -->
<link href="http://cdn-images.mailchimp.com/embedcode/classic-081711.css" rel="stylesheet" type="text/css">
<div id="mc_embed_signup">
	<form action="http://herokuapp.us7.list-manage2.com/subscribe/post?u=3484f4ecdb03c17723ecec26d&amp;id=a409943dbb" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
	
		<div class="mc-field-group">
			<label for="mce-EMAIL">Email Address  <span class="asterisk">*</span>
		</label>
			<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
		</div>
		<div class="mc-field-group">
			<label for="mce-FNAME">First Name </label>
			<input type="text" value="" name="FNAME" class="" id="mce-FNAME">
		</div>
		<div class="mc-field-group">
			<label for="mce-LNAME">Last Name </label>
			<input type="text" value="" name="LNAME" class="" id="mce-LNAME">
		</div>

		<div class="indicates-required"><span class="asterisk">*</span> indicates required</div>

		<div id="mce-responses" class="clear">
			<div class="response" id="mce-error-response" style="display:none"></div>
			<div class="response" id="mce-success-response" style="display:none"></div>
		</div>	
		
		<div class="clear">
			<input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button">
		</div>

	</form>
</div>



</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<%= render 'layouts/head' %>

<body>

	<section id="pre-header"></section>

	<header>

		<%= render 'layouts/header' %>

	</header>


	<section id="container">
					
		<section class="content">
			
			<%= yield %>

		</section>

		<aside>			
			
			<%= render 'layouts/sidebar' %>

		</aside>

	</section>


	<footer>

		<%= render 'layouts/footer' %>
				
	</footer>

</body>
</html>

app/views/main/home.html.erb
<section class="text">
<p>The Musical Waves house concert series brings the sounds of Baroque Music to the cliffs of San Francisco. Founded in 2009 by harpsichordist Elaine Thornburgh/Ilana Bar-David, audiences are able to enjoy intimate solo and ensemble concerts overlooking Sutro Heights Park next to The Cliff House.
</p>

</section>

 <% program = next_program unless next_program == nil %>
 <% if program == nil %>
 <h4>Unfortunately no concerts are currently coming up, but stay tuned by subscribing to the email list!</h4>
 <% else %>
  <h5>Upcoming Concerts:</h5>
  <br>
  <article id="program">
    <h2><%= link_to program.title, p_show_path(:title => program.title) %></h2>
    <h4><%= artist_list(program).html_safe %></h4>
    <p></p>
    <section class="concert-box">
      <% concert_sort(program).each do |concert| %>
        <div>  
          <h5>Date:</h5><h6><%= concert.date.strftime('%A %B %d, %Y') %></h6>
          <h5>Time:</h5><h6><%= concert.time %></h6>
          <h5>Location:</h5><h6><%= concert.location %></h6>
        </div>
      <% end %>
    </section>
    <section class="text">
      <p>
        <%= truncate(strip_tags(program.description), :length=>220) %>
      </p>
    </section>

    <a href="<%= p_show_path(:title => program.title) %>" class="button">More Information</a>

  </article>
  <% end %>

app/views/main/music.html.erb
<h1>Music</h1>
<section class="text">
<p>A selection of Elaine Thornburgh's Youtube videos are below and if you are interested in purchasing CDs, you can buy them from the artist at the concerts.</p>
</section>


<h4>J.S. Bach's Goldberg Variations: Aria</h4>
<p>
<iframe width="560" height="315" src="//www.youtube.com/embed/JO3cV1Uw-_o?rel=0" frameborder="0" allowfullscreen></iframe>
</p>

<h4>François Couperin's Les Silvains</h4>
<p>
<iframe width="560" height="315" src="//www.youtube.com/embed/vK5dyNR5A9Y?rel=0" frameborder="0" allowfullscreen></iframe>
</p>

<h4>François Couperin's 4th Prelude</h4>
<p>
<iframe width="560" height="315" src="//www.youtube.com/embed/mPQMOw2OI-A?rel=0" frameborder="0" allowfullscreen></iframe>
</p>

app/views/programs/index.html.erb
<h1>Upcoming Concerts</h1>
 <% if future_programs(@programs) == [] %>
 <h4>No concerts are currently coming up, but stay tuned!</h4>
 <% else %>
<section class="list">
  <% program_sort(future_programs(@programs)).each do |program| %>
  <article id="program">
    <h2><%= link_to program.title, p_show_path(:title => program.title) %></h2>
    <h4><%= artist_list(program).html_safe %></h4>
    <p></p>
    <section class="concert-box">
      <% concert_sort(program).each do |concert| %>
        <div>  
          <h5>Date:</h5><h6><%= concert.date.strftime('%A %B %d, %Y') %></h6>
          <h5>Time:</h5><h6><%= concert.time %></h6>
          <h5>Location:</h5><h6><%= concert.location %></h6>
        </div>
      <% end %>
    </section>
    <section class="text">
      <p>
        <%= truncate(strip_tags(program.description), :length=>220) %>
      </p>
    </section>

    <a href="<%= p_show_path(:title => program.title) %>" class="button">More Information</a>

  </article>
  <% end %>
</section>
<% end %>
<p></p>
<h1>Past Programs</h1>

<section class="list">
  <% program_sort(past_programs(@programs)).each do |program| %>
  <article id="program">
    <h3><%= link_to program.title, p_show_path(:title => program.title) %></h3>
    <h5><%= artist_list(program).html_safe %></h5>
    <section class="text">
      <p>
        <%= truncate(strip_tags(program.description), :length=>220) %>
      </p>
    </section>

    <a href="<%= p_show_path(:title => program.title) %>" class="button">More Information</a>

  </article>
  <% end %>
</section>

app/views/programs/show.html.erb
<article id="program">
  <h2><%= @program.title %></h2>
  <h4><%= artist_list(@program).html_safe %></h4>
  <p></p>
  <section class="concert-box">
    <% concert_sort(@program).each do |concert| %>
      <div>
        <h5>Date:</h5><h6><%= concert.date.strftime('%A %B %d, %Y') %></h6>
        <h5>Time:</h5><h6><%= concert.time %></h6>
        <h5>Location:</h5><h6><%= concert.location %></h6>
        <% if !concert.price.nil? %>
          <h5>Price:</h5><h6>$<%= concert.price %></h6>
        <% end %>
        <% if !concert.ticket_website.empty? %>
          <a href="<%=concert.ticket_website %>" class="button" id="ticket-button">Buy Tickets</a>
        <% end %>
      </div>
   <% end %>
  </section>
  <section class="text">
    <p>
      <%= @program.description.html_safe %>
    </p>
  </section>

  <% if !@program.website.empty? %>
    <a href="<%=@program.website %>" class="button">More About the Program</a>
  <% end %>
  
  <section class="list">
    <% @program.artists.each do |artist| %>
      <article class="artist-small">
        <% if !artist.picture.empty? %>
          <a href="<%= artist.picture %>"><img src="<%= artist.picture %>" alt="" class="" id="thumbnail"/></a>
        <% end %>
        <h3><%= link_to artist.name, a_show_path(:name => artist.name) %></h3>
        <h5><%= artist.instrument %></h5>
        <a href="<%= a_show_path(:name => artist.name) %>" class="button" id="artist-button">About Artist</a>
      </article>
    <% end %>
  </section>

</article>

<stron><%= link_to "Back to Concerts", concerts_path %></strong>